In [1]:
import numpy as np
import pandas as pd
from PIL import Image

In [2]:
def get_data_from_coords_and_file(x_list, y_list, filename):
    im = np.array(Image.open(filename))
    return im[x_list, y_list]

In [18]:
im = np.array(Image.open("data/KRA_VINEYARDS_100m.tif"))
real_coords = np.argwhere(im == True).T

array([[ 197,  197,  198, ..., 2939, 2939, 2939],
       [2445, 2446, 2442, ..., 1362, 1363, 1364]])

In [4]:
def get_data_df(coords, features_files):
    data = {}
    data["x"] = coords[0]
    data["y"] = coords[1]
    for feature, filename in features_files:
        data[feature] = get_data_from_coords_and_file(coords[0], coords[1], filename)
    return pd.DataFrame.from_dict(data)

In [11]:
def get_coords_from_file(filename):
    lines = []
    with open(filename, "r") as f:
        lines = f.readlines()
        lines = lines[1:]
    coords = [[], []]
    for line in lines:
        _, x, y = line.split()
        coords[0].append((int(x) - 310050) // 100)
        coords[1].append((int(y) - 4800050) // 100)
    return coords

In [12]:
coords = get_coords_from_file("data/VINEYARDS.TXT")

In [13]:
features_place = [
    ("admin", "data/KRA_ADMIN_100m.tif"),
    ("landcover", "data/KRA_LANDCOVER_100m.tif"),
    # ("prec", "data/KRA_PREC_100m.tif"),
    ("relief_aspect", "data/KRA_RELIEF_ASPECT_100m.tif"),
    ("relief_height", "data/KRA_RELIEF_HEIGHT_100m.tif"),
    ("relief_slope", "data/KRA_RELIEF_SLOPE_100m.tif"),
    ("relief_soiltexture", "data/KRA_SOILTEXTURE_100m.tif"),
    ("sunny_days", "data/KRA_SUNNY_DAYS_APR_OCT_100m.tif"),
    # ("tavg", "data/KRA_TAVG_100m.tif"),
    # ("tmax", "data/KRA_TMAX_100m.tif"),
    # ("tmin", "data/KRA_TMIN_100m.tif"),
    ("vineyard", "data/KRA_VINEYARDS_100m.tif"),
    ("water_seasonality", "data/KRA_WATER_SEASONALYTY_100m.tif")
]

In [19]:
tmp = get_data_df(real_coords, features_place)

In [21]:
tmp

,x,y,admin,landcover,relief_aspect,relief_height,relief_slope,relief_soiltexture,sunny_days,vineyard,water_seasonality
0,197,2445,False,7,360.000000,17,1.432096,3,111,True,0
1,197,2446,False,7,18.434948,17,0.905850,3,111,True,0
2,198,2442,False,5,18.434948,21,0.905850,3,111,True,0
3,198,2443,False,5,11.309933,20,1.460445,3,111,True,0
4,198,2444,False,5,11.309933,20,1.460445,3,111,True,0
...,...,...,...,...,...,...,...,...,...,...,...
35581,2938,1363,True,5,186.009003,58,10.816006,6,128,True,0
35582,2938,1364,True,7,169.315094,58,15.092257,6,128,True,0
35583,2939,1362,True,5,217.954224,35,17.591572,0,128,True,12
35584,2939,1363,True,5,180.000000,46,10.481218,6,128,True,0
35585,2939,1364,True,2,156.801407,35,14.925286,6,128,True,0

In [22]:
tmp.to_csv("data.csv", index=False)